services:
  loki:
    image: grafana/loki:3.1.1
    container_name: loki
    user: "0"
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config/config.yml
    volumes:
      - .configs/grafana/loki.yml:/etc/loki/config/config.yml
      - loki-data:/tmp/loki

  promtail:
    image: grafana/promtail:3.1.1
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - .configs/grafana/promtail.yml:/etc/promtail/config.yml
      - ./nestjs-logs:/nestjs-logs
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    ports:
      - "3201:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - loki
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=glonghini
      - GF_SECURITY_ADMIN_PASSWORD=glonghini123

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - .configs/grafana/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nestjs
      POSTGRES_PASSWORD: nestjs123
      POSTGRES_DB: nestjs_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nestjs"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine3.22
    container_name: nest-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=nestjs
      - DB_PASSWORD=nestjs123
      - DB_NAME=nestjs_db
      - REDIS_HOST=nest-redis
      - REDIS_PORT=6379
      - LOG_LEVEL=info
    depends_on:
      - postgres
      - redis
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  loki-data:
  postgres-data:
  grafana_data:
  redis-data:
